workflow changes

diff --git a/.github/workflows/run-bench.yml b/.github/workflows/run-bench.yml
--- a/.github/workflows/run-bench.yml
+++ b/.github/workflows/run-bench.yml
@@ -8,32 +8,21 @@ on:
   pull_request:
 
 jobs:
-  run-bench:
+  test-avx512:
+    concurrency:
+      group: ${{ matrix.isa }}-${{ matrix.jdk }}
+      cancel-in-progress: false
     strategy:
       matrix:
-        jdk: [11, 20, 22, 24]
-        os: [ubuntu-latest, windows-latest]
-        isa: [isa-avx512f]
-    runs-on: ${{ matrix.os }}
+        jdk: [ 20, 24 ]
+        isa: [ isa-avx512f ]
+    runs-on: ${{ matrix.isa }}
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up JDK ${{ matrix.jdk }}
-        uses: actions/setup-java@v4
-        with:
-          distribution: 'temurin'
-          java-version: ${{ matrix.jdk }}
-
-      - name: Set up GCC
-        if: matrix.os == 'ubuntu-latest'
-        run: sudo apt install -y gcc
-
-      - name: Print ISA info
-        if: matrix.os == 'ubuntu-latest'
+      - name: verify-avx512
         run: |
+          # avx2 is included just for illustration
           required="avx2 avx512f avx512cd avx512bw avx512dq avx512v"
-          printf "required ISA feature flags: %s\n" "${required}"
+          printf "required ISA feature flags: %s\n" "${required}" 
           flags="$(lscpu|grep '^Flags'|cut -d: -f2)"
           output=""
           for flag in ${required} ; do
@@ -42,22 +31,21 @@ jobs:
            else output="${output} $flag(FAIL)"
           fi ; done
           printf "%s\n" ${output}
-          if [[ " $output " == *"FAIL"* ]]; then
-            echo "Warning: Missing required AVX-512 flags. Skipping AVX-512 benchmarks."
-            exit 0
-          fi
-
-      - name: Build with Maven (JDK 11)
-        if: matrix.jdk == '11'
-        run: mvn -B -Pjdk11 package --file pom.xml
+          if [[ " $output " == *"FAIL"* ]] ; then exit 2 ; fi
+      - name: Set up GCC
+        run: |
+          sudo apt install -y gcc
+      - uses: actions/checkout@v4
+      - name: Set up JDK ${{ matrix.jdk }}
+        uses: actions/setup-java@v3
+        with:
+          java-version: ${{ matrix.jdk }}
+          distribution: temurin
+          cache: maven
 
       - name: Build with Maven (JDK 20)
         if: matrix.jdk == '20'
         run: mvn -B -Pjdk20 package --file pom.xml
-
-      - name: Build with Maven (JDK 22)
-        if: matrix.jdk == '22'
-        run: mvn -B package --file pom.xml
 
       - name: Build with Maven (JDK 24)
         if: matrix.jdk == '24'
