instrument of required vectorization provider

diff --git a/.github/workflows/unit-tests.yaml b/.github/workflows/unit-tests.yaml
--- a/.github/workflows/unit-tests.yaml
+++ b/.github/workflows/unit-tests.yaml
@@ -18,10 +18,25 @@ jobs:
       cancel-in-progress: false
     strategy:
       matrix:
-        jdk: [ 20, 22]
+#        jdk: [ 20, 22]
+        jdk: [ 22]
         isa: [ isa-avx512f ]
     runs-on: ${{ matrix.isa }}
     steps:
+      - name: verify-avx512
+        run: |
+          # avx2 is included just for illustration
+          required="avx2 avx512f avx512cd avx512bw avx512dq avx512v"
+          printf "required ISA feature flags: %s\n" "${required}" 
+          flags="$(lscpu|grep '^Flags'|cut -d: -f2)"
+          output=""
+          for flag in ${required} ; do
+           if [[ " $flags " == *"${flag}"* ]]
+           then output="${output} $flag(OK)"
+           else output="${output} $flag(FAIL)"
+          fi ; done
+          printf "%s\n" ${output}
+          if [[ " $output " == *"FAIL"* ]] ; then exit 2 ; fi
       - uses: actions/checkout@v4
       - name: Set up JDK
         uses: actions/setup-java@v3
@@ -30,11 +45,17 @@ jobs:
           distribution: temurin
           cache: maven
       - name: Compile, run tests, and package (JDK 20)
+        if: matrix.jdk == '20'
         run: mvn -X -B -Pjdk20 -am -pl jvector-tests test
-        if: matrix.jdk == '20'
       - name: Compile, run tests, and package (JDK 22)
-        run: mvn -X -B verify
         if: matrix.jdk == '22'
+        run: |
+         # first, a coherence check on testing config, requires native vectorization
+         mvn -X -B -Dsurefire.failIfNoSpecifiedTests=false -Dtest=NativeVectorUtilSupportTest \
+          -DTest_RequireNativeVectorizationProvider=NativeVectorizationProvider \
+          verify
+         # then, everything else is tested
+         mvn -X -B verify
       - name: Test Summary
         if: always()
         uses: test-summary/action@v2
@@ -43,37 +64,37 @@ jobs:
             **/target/surefire-reports/TEST-*.xml
 
 
-  build:
-    concurrency:
-        group: ${{ github.ref }}-${{ github.job }}-${{ matrix.jdk }}-${{ matrix.os }}
-        cancel-in-progress: true
-    strategy:
-      matrix:
-        jdk: [ 11, 20, 22]
-        os: [ ubuntu-latest, windows-latest ]
-    runs-on: ${{ matrix.os }}
-    steps:
-      - uses: actions/checkout@v4
-      - name: Set up JDK
-        uses: actions/setup-java@v3
-        with:
-          java-version: ${{ matrix.jdk }}
-          distribution: temurin
-          cache: maven
-      - name: Compile, run tests, and package (JDK 22)
-        run: mvn -B verify
-        if: matrix.jdk == '22'
-      - name: Compile, run tests, and package (JDK 20)
-        run: mvn -B -Pjdk20 -am -pl jvector-tests test
-        if: matrix.jdk == '20'
-      - name: Compile and run tests (JDK 11)
-        run: mvn -B -Pjdk11 -am -pl jvector-tests test
-        if: matrix.jdk == '11'
-      - name: Test Summary
-        if: always()
-        uses: test-summary/action@v2
-        with:
-          paths: |
-            **/target/surefire-reports/TEST-*.xml
+#  build:
+#    concurrency:
+#        group: ${{ github.ref }}-${{ github.job }}-${{ matrix.jdk }}-${{ matrix.os }}
+#        cancel-in-progress: true
+#    strategy:
+#      matrix:
+#        jdk: [ 11, 20, 22]
+#        os: [ ubuntu-latest, windows-latest ]
+#    runs-on: ${{ matrix.os }}
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Set up JDK
+#        uses: actions/setup-java@v3
+#        with:
+#          java-version: ${{ matrix.jdk }}
+#          distribution: temurin
+#          cache: maven
+#      - name: Compile, run tests, and package (JDK 22)
+#        run: mvn -B verify
+#        if: matrix.jdk == '22'
+#      - name: Compile, run tests, and package (JDK 20)
+#        run: mvn -B -Pjdk20 -am -pl jvector-tests test
+#        if: matrix.jdk == '20'
+#      - name: Compile and run tests (JDK 11)
+#        run: mvn -B -Pjdk11 -am -pl jvector-tests test
+#        if: matrix.jdk == '11'
+#      - name: Test Summary
+#        if: always()
+#        uses: test-summary/action@v2
+#        with:
+#          paths: |
+#            **/target/surefire-reports/TEST-*.xml
 
         
